### PR TITLE
Fix/appmesh index out of bounds

### LINKED ISSUE #835: Index out of bounds error when performing `meshctl get meshes` when appmesh discovery is enabled
**Describe the bug**
After enabling `appmesh` discovery, when performing `meshctl get meshes` I receive an index out of bounds error message, instead of being show the table with discovered meshes.

**To Reproduce**
1. Deploy 2 AWS EKS clusters
1. Create an `appmesh` instance in one of the clusters. You can follow [this guide](https://www.eksworkshop.com/advanced/320_servicemesh_with_appmesh/) for a how to.
1. Follow the steps described in the [appmesh guide](https://github.com/solo-io/service-mesh-hub/blob/master/docs/content/guides/appmesh_guide.md)
2. From the guide, enable `appmesh` discovery for the region:
   ```yaml
    apiVersion: core.smh.solo.io/v1alpha1
    kind: Settings
    metadata:
      namespace: service-mesh-hub
      name: settings
    spec:
      aws:
        disabled: false
        accounts:
          - accountId: "<aws-account-id>"
            meshDiscovery:
              resourceSelectors:
              - matcher:
                  regions:
                  - us-east-2
            eksDiscovery:
              disabled: true
    ```
3. Perform `meshctl get meshes`

**Expected behavior**
I should be shown a table with discovered appmesh instances

**Actual behavior**
I get an index out of bounds error:
```
panic: runtime error: index out of range [4] with length 4

goroutine 1 [running]:
github.com/solo-io/service-mesh-hub/cli/pkg/common/table_printing/internal.FilterEmptyColumns(0xc000c74c40, 0x4, 0x4, 0xc000c8e570, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/harvey/service-mesh-hub/cli/pkg/common/table_printing/internal/filter.go:33 +0x82d
github.com/solo-io/service-mesh-hub/cli/pkg/common/table_printing.(*meshPrinter).printAwsAppMeshMeshes(0xc0003a5be0, 0x27d78e0, 0xc00000e018, 0xc0006afad0, 0x2, 0x2, 0x0, 0x0)
	/Users/harvey/service-mesh-hub/cli/pkg/common/table_printing/mesh_printer.go:220 +0x88c
github.com/solo-io/service-mesh-hub/cli/pkg/common/table_printing.(*meshPrinter).Print(0xc0003a5be0, 0x27d78e0, 0xc00000e018, 0xc000505940, 0x3, 0x3, 0x0, 0x0)
	/Users/harvey/service-mesh-hub/cli/pkg/common/table_printing/mesh_printer.go:46 +0x2f1
github.com/solo-io/service-mesh-hub/cli/pkg/tree/get/mesh.GetMeshes(0x2816e80, 0xc0000440e0, 0x27d78e0, 0xc00000e018, 0x27d5e60, 0xc0003a5be0, 0x27d5e80, 0xc0000964e8, 0x27d5ea0, 0xc0000964f0, ...)
	/Users/harvey/service-mesh-hub/cli/pkg/tree/get/mesh/get_mesh_client.go:45 +0x804
github.com/solo-io/service-mesh-hub/cli/pkg/tree/get/mesh.GetMeshRootCommand.func1(0xc0000118c0, 0x371b300, 0x0, 0x0, 0x0, 0x0)
	/Users/harvey/service-mesh-hub/cli/pkg/tree/get/mesh/get_mesh_root_cmd.go:36 +0x164
github.com/spf13/cobra.(*Command).execute(0xc0000118c0, 0x371b300, 0x0, 0x0, 0x0, 0x0)
	/Users/harvey/.gvm/pkgsets/go1.14/global/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0xb21
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000158c0, 0xc0000118c0, 0x0, 0x0)
	/Users/harvey/.gvm/pkgsets/go1.14/global/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x6d7
github.com/spf13/cobra.(*Command).Execute(0xc0000158c0, 0x0, 0x0)
	/Users/harvey/.gvm/pkgsets/go1.14/global/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885 +0x3b
main.main()
	/Users/harvey/service-mesh-hub/cli/cmd/main.go:12 +0x8f
```

**Additional context**
Add any other context about the problem here, e.g.
- Service Mesh Hub version
```
Client: {"version":"0.6.0"}
Server: {"Namespace":"service-mesh-hub","Containers":[{"domain":"docker.io","path":"soloio/mesh-discovery","tag":"0.6.0"},{"domain":"docker.io","path":"soloio/mesh-networking","tag":"0.6.0"}]}
```
- Kubernetes version
`1.5`
- service mesh and version 
`appmesh`

### PR DESCRIPTION
**Pull request by mihmatache**
Updated the `printAwsAppMesh` method, as the `appmesh` information has differences between it and the common case.

Print info:

```
Aws AppMesh:
+----------------+--------------------+-----------+----------------+-----------+
|      NAME      |      CLUSTERS      | MESH NAME | AWS ACCOUNT ID |  REGION   |
+----------------+--------------------+-----------+----------------+-----------+
| appmesh-mesh-1 | cluster-1          | mesh-name | 1234567        | us-east-2 |
|                | cluster-2          |           |                |           |
+----------------+--------------------+-----------+----------------+-----------+

``` 

BOT NOTES:
resolves #835 

BOT NOTES: 
resolves https://github.com/solo-io/service-mesh-hub/issues/835

### CODE REVIEW

File: cli/pkg/common/table_printing/mesh_printer.go [hunk 1]
```diff
@@ -190,29 +190,34 @@ func (m *meshPrinter) printAwsAppMeshMeshes(out io.Writer, meshes []*smh_discove
...
-	fmt.Fprintln(out, "\nAws AppMesh:")
+	_, _ = fmt.Fprintln(out, "\nAws AppMesh:")
 
 	table := m.tableBuilder(out)
 
-	commonHeaderRows := append([]string{}, m.commonHeaderRows...)
+	commonHeaderRows := []string{
+		"Name",
+		"Clusters",
+		"Mesh Name",
```
Comment (harveyxia) [inline cli/pkg/common/table_printing/mesh_printer.go:200]: I would name this "App Mesh Name" for clarity

**Comment by harveyxia** [comment]
e2e tests are failing on the Appmesh EKS tests because github secrets aren't available to PRs from forked repos, we may need to switch to a different CI environment to work around this issue. I'm merging in the mean time since this change doesn't touch the appmesh/eks logic
